// Code generated by configgen from ../../configs/default.yaml; DO NOT EDIT.
// To regenerate: go generate ./...
//
// WingFC Configuration
// All user-configurable parameters and hardware mappings
//
// All the configurable values are defined here, making it easy to tune the
// flight controller without changing the main application logic.

package main

//go:generate go run ../../tools/configgen -config ../../configs/default.yaml -out config.go

// --- Protocol Settings ---
const (
	NumChannels = 16
)

// --- Board Orientation ---
// 0: Default, 1: CW90, 2: CW180, 3: CW270, 4: flip, 5: flipCW90, 6: flipCW180, 7: flipCW270
const ORIENTATION = 0

// Set your aircraft type here
// Options:
// AIRFRAME_ELEVON
// AIRFRAME_SINGLE_AILERON_T_TAIL
// AIRFRAME_DUAL_AILERON_T_TAIL
// AIRFRAME_SINGLE_AILERON_V_TAIL
// AIRFRAME_DUAL_AILERON_V_TAIL
const AIRCRAFT_TYPE = AIRFRAME_ELEVON

// --- Receiver Configuration ---
const (
	AileronChannel    = 0 // CH1 (Roll)
	ElevatorChannel   = 1 // CH2 (Pitch)
	ThrottleChannel   = 2 // CH3 (Throttle)
	YawChannel        = 3 // CH4 (Yaw)
	ArmChannel        = 4 // CH5
	ManualModeChannel = 7 // CH6

	TuningChannelA = 5 // CH7 for tuning parameter A
	TuningChannelB = 6 // CH8 for tuning parameter B
	TuningChannelC = 8 // CH9 for tuning parameter C
	TuningChannelD = 9 // CH10 for tuning parameter D
)

// --- PWM & Hardware Configuration ---
const (
	// Use DShot for ESC throttle control, so no traditional PWM channel for throttle is needed.
	// DSHOT_MODE can be 150, 300, or 600 (representing DShot150, DShot300, DShot600)
	DSHOT      = false
	DSHOT_MODE = 600

	// PWM Frequencies
	SERVO_PWM_FREQUENCY = 100 // 50Hz for analog servos
	ESC_PWM_FREQUENCY   = 400 // 400Hz for high-speed ESC

	DEADBAND      = 10
	HIGH_RX_VALUE = 1800

	// RC Receiver channel value constants
	MIN_RX_VALUE     = 988
	MAX_RX_VALUE     = 2012
	NEUTRAL_RX_VALUE = 1500
)

// --- Servo Configuration (Limits, Trims, & Reversals) ---
const (
	// Servo 1: Primary Aileron / Left Elevon
	SERVO1_MIN     = 1100
	SERVO1_MAX     = 1900
	SERVO1_SUBTRIM = 0
	SERVO1_REVERSE = false

	// Servo 2: Primary Elevator / Right Elevon
	SERVO2_MIN     = 1100
	SERVO2_MAX     = 1900
	SERVO2_SUBTRIM = 0
	SERVO2_REVERSE = false

	// Servo 4: Rudder / V-Tail
	SERVO4_MIN     = 1100
	SERVO4_MAX     = 1900
	SERVO4_SUBTRIM = 0
	SERVO4_REVERSE = false

	// Servo 5: Secondary Aileron
	SERVO5_MIN     = 1100
	SERVO5_MAX     = 1900
	SERVO5_SUBTRIM = 0
	SERVO5_REVERSE = false

	// Servo 6: Aux
	SERVO6_MIN     = 1100
	SERVO6_MAX     = 1900
	SERVO6_SUBTRIM = 0
	SERVO6_REVERSE = false
)

// --- Flight Control Parameters ---
const (
	MAX_PITCH_RATE_DEG = 200
	MAX_ROLL_RATE_DEG  = 600
	MAX_YAW_RATE_DEG   = 100

	// Maximum stabilized-mode angle commands from stick (degrees)
	// Stick at full deflection commands this many degrees of desired tilt.
	MAX_PITCH_ANGLE_DEG float32 = 45.0
	MAX_ROLL_ANGLE_DEG  float32 = 60.0

	PID_WEIGHT float32 = 0.5

	// Low-pass filter levels (applied independently to accel and gyro).
	// 0 = no filtering, 1 = mild (α≈0.25, >>2), 2 = stronger (α≈0.125, >>3)
	//
	// Gyros are low-noise — keep at 0 for maximum stabilization responsiveness.
	// Accelerometers are vibration-prone — heavier filtering is appropriate.
	LPF_ACCEL_LEVEL = 2
	LPF_GYRO_LEVEL  = 0

	// PID Gains
	// D gain is intentionally 0: the derivative term amplifies noise by 1/dt (×200 at 200Hz).
	// Tune P and I first; only add D if oscillation persists after P/I are dialled in.
	pP, pI, pD float32 = 1.00, 0.050, 0.00
	rP, rI, rD float32 = 1.00, 0.050, 0.00
	yP, yI, yD float32 = 0.50, 0.020, 0.00 // Yaw PID gains
)

// --- Tuning Parameters ---
// Set TuneParameter to 0 to disable tuning, or 1-6 to enable
const (
	// Parameter selection (0 = disabled)
	// 1: Pitch P, 2: Roll P
	// 3: Pitch I, 4: Roll I
	// 5: Pitch D, 6: Roll D
	TuneParameterA = 0 // Disabled by default
	TuneParameterB = 0
	TuneParameterC = 0
	TuneParameterD = 0

	// Parameter ranges (adjusted via stick position 988-2012)
	TuneParameterAmin float32 = 0.1000
	TuneParameterAmax float32 = 2.0000

	TuneParameterBmin float32 = 0.0100
	TuneParameterBmax float32 = 0.5000

	TuneParameterCmin float32 = 0.0010
	TuneParameterCmax float32 = 0.1000

	TuneParameterDmin float32 = 0.0010
	TuneParameterDmax float32 = 0.1000
)
